name: Python Script Workflow
permissions:
   contents: read
on:
  push:
    branches:
      - main

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Get changed files
    outputs:
      matrix: ${{ steps.changed-files-specific.outputs.all_changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.py
          matrix: true

      - name: List all changed files
        run: echo '${{ steps.changed-files-specific.outputs.all_changed_files }}'

  run-python:
    if: needs.changed-files.outputs.matrix != []
    runs-on: ubuntu-latest
    name: Run python
    needs: [changed-files]
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.13'
      - name: Run python on ${{ matrix.files }}
        run: python ${{ matrix.files }}